"""
Search PDF Exporter
===================
Generates a branded PDF report from keyword search results.
Each result page contains:
  - Header: newspaper name, date, page number badge
  - Full newspaper page image (actual scanned snapshot)
  - Keyword context highlight
  - Translated English headline + article text
  - OCR confidence footnote
"""

import io
import logging
import re
import textwrap
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from PIL import Image, ImageDraw, ImageFont
import pypdf
from pypdf import PdfWriter

from harvester.config import settings, EXPORTS_DIR

logger = logging.getLogger("harvester.search_pdf_exporter")

# Page dimensions (A4 landscape equivalent at 150 DPI)
PAGE_W = 1200
PAGE_H = 1700

# Colour palette
COL_HEADER_BG = (15, 23, 42)       # dark navy
COL_HEADER_TEXT = (255, 255, 255)
COL_ACCENT = (56, 189, 248)        # cyan
COL_BADGE_BG = (239, 68, 68)       # red badge for page number
COL_BADGE_TEXT = (255, 255, 255)
COL_BODY_BG = (248, 248, 248)
COL_BODY_TEXT = (30, 41, 59)
COL_SNIPPET_BG = (254, 249, 195)   # yellow highlight
COL_SNIPPET_TEXT = (120, 53, 15)
COL_BORDER = (203, 213, 225)
COL_FOOTNOTE = (100, 116, 139)
COL_TITLE_PAGE_BG = (15, 23, 42)


def _load_font(size: int, bold: bool = False):
    font_names = (
        ["arialbd.ttf", "Arial_Bold.ttf", "DejaVuSans-Bold.ttf"]
        if bold
        else ["arial.ttf", "Arial.ttf", "DejaVuSans.ttf"]
    )
    for name in font_names:
        try:
            return ImageFont.truetype(name, size)
        except IOError:
            pass
    return ImageFont.load_default()


def _draw_wrapped_text(
    draw: ImageDraw.ImageDraw,
    text: str,
    x: int,
    y: int,
    max_width: int,
    font,
    fill,
    line_spacing: int = 6,
) -> int:
    """Draw wrapped text, return new Y position after last line."""
    if not text:
        return y
    # Estimate chars per line from font size
    try:
        bbox = font.getbbox("A")
        char_w = bbox[2] - bbox[0] if bbox else 12
    except Exception:
        char_w = 12
    chars_per_line = max(20, max_width // max(char_w, 1))
    lines = []
    for para in text.split("\n"):
        wrapped = textwrap.wrap(para, width=chars_per_line) if para.strip() else [""]
        lines.extend(wrapped)
    try:
        bbox = font.getbbox("Ag")
        line_h = (bbox[3] - bbox[1]) + line_spacing
    except Exception:
        line_h = 24
    for line in lines:
        if y > PAGE_H - 60:
            break
        draw.text((x, y), line, font=font, fill=fill)
        y += line_h
    return y


def _build_title_page(
    keyword: str,
    source_names: List[str],
    date_label: str,
    result_count: int,
) -> bytes:
    """Renders a branded cover page for the search result PDF."""
    img = Image.new("RGB", (PAGE_W, PAGE_H), color=COL_TITLE_PAGE_BG)
    draw = ImageDraw.Draw(img)

    # Gradient-like header stripe
    for i in range(120):
        shade = int(15 + i * 1.2)
        draw.rectangle([(0, i), (PAGE_W, i + 1)], fill=(shade, shade + 10, shade + 40))

    # Logo area
    draw.rectangle([(40, 40), (PAGE_W - 40, 130)], outline=COL_ACCENT, width=2)
    f_big = _load_font(52, bold=True)
    draw.text((60, 50), "📰 VEE2 ePaper Intelligence", font=f_big, fill=COL_ACCENT)

    # Title
    f_title = _load_font(44, bold=True)
    draw.text((60, 190), "Keyword Search Report", font=f_title, fill=(255, 255, 255))

    # Keyword badge
    kw_label = f'"{keyword}"'
    f_kw = _load_font(36, bold=True)
    draw.rounded_rectangle([(60, 270), (PAGE_W - 60, 340)], radius=12, fill=(56, 189, 248, 220))
    draw.text((80, 280), f"🔍  Keyword: {kw_label}", font=f_kw, fill=(15, 23, 42))

    # Meta info
    f_meta = _load_font(26)
    y = 380
    draw.text((60, y), f"📅  Date: {date_label}", font=f_meta, fill=(148, 163, 184))
    y += 50
    draw.text((60, y), f"📊  Results Found: {result_count} matching pages", font=f_meta, fill=(148, 163, 184))
    y += 50
    draw.text((60, y), f"📰  Sources: {', '.join(source_names) or 'All'}", font=f_meta, fill=(148, 163, 184))

    # Divider
    y += 80
    draw.line([(60, y), (PAGE_W - 60, y)], fill=COL_ACCENT, width=2)
    y += 30

    # Info block
    f_body = _load_font(22)
    info_lines = [
        "This report was automatically generated by VEE2 ePaper Intelligence.",
        "Each page below shows the actual newspaper page image, translated headline,",
        "full English article text, OCR confidence score, and source page number.",
        "",
        "OCR Engine: RapidOCR + Multilingual Tesseract",
        "Translation: LLM-powered with Named Entity Preservation",
        "Newspapers: DT Next | Lokmat | Loksatta | Financial Express",
    ]
    for line in info_lines:
        draw.text((60, y), line, font=f_body, fill=(100, 116, 139))
        y += 36

    # Footer
    draw.rectangle([(0, PAGE_H - 60), (PAGE_W, PAGE_H)], fill=(10, 15, 30))
    f_footer = _load_font(20)
    ts = datetime.now().strftime("%d %B %Y, %I:%M %p IST")
    draw.text((60, PAGE_H - 42), f"Generated: {ts}  |  VEE2 Automated ePaper Harvester  |  Confidential",
              font=f_footer, fill=(71, 85, 105))

    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=90)
    buf.seek(0)
    return buf.read()


def _build_result_page(result: Dict[str, Any], keyword: str, index: int, total: int) -> bytes:
    """Renders one result page: header + newspaper page image + translated text."""
    img = Image.new("RGB", (PAGE_W, PAGE_H), color=COL_BODY_BG)
    draw = ImageDraw.Draw(img)

    source_name = result.get("source_name", "Newspaper")
    date_str = result.get("date", "")
    page_num = result.get("page_num", 1)
    ocr_conf = result.get("ocr_confidence", 0.9)
    orig_lang = result.get("original_language", "")
    story = result.get("story") or {}

    headline = story.get("title") or result.get("snippet_en", "")[:100]
    body_text = story.get("snippet") or result.get("ocr_text_en", "")
    orig_headline = story.get("original_title", "")

    # ---- HEADER BAR ----
    draw.rectangle([(0, 0), (PAGE_W, 80)], fill=COL_HEADER_BG)
    f_hdr = _load_font(28, bold=True)
    draw.text(
        (20, 12),
        f"📰  {source_name.upper()}   ·   {date_str}",
        font=f_hdr,
        fill=COL_HEADER_TEXT,
    )

    # Page badge (top right)
    badge_text = f"Page {page_num}"
    f_badge = _load_font(22, bold=True)
    draw.rounded_rectangle([(PAGE_W - 150, 15), (PAGE_W - 20, 65)], radius=8, fill=COL_BADGE_BG)
    draw.text((PAGE_W - 140, 28), badge_text, font=f_badge, fill=COL_BADGE_TEXT)

    # Result counter
    f_ctr = _load_font(18)
    draw.text((20, 60), f"Result {index} of {total}", font=f_ctr, fill=COL_ACCENT)

    y = 90

    # ---- NEWSPAPER CLIPPING IMAGE (CROPPED & HIGHLIGHTED) ----
    snap_path = result.get("snapshot_path")
    img_loaded = False
    if snap_path and Path(snap_path).exists():
        try:
            from harvester.news.news_cropper import generate_news_crop
            crop_path = generate_news_crop(Path(snap_path), query=keyword, story=story)
            img_to_use = crop_path if (crop_path and crop_path.exists()) else Path(snap_path)

            page_img = Image.open(img_to_use).convert("RGB")
            max_w = PAGE_W - 40
            max_h = 680
            page_img.thumbnail((max_w, max_h), Image.LANCZOS)
            img_x = (PAGE_W - page_img.width) // 2
            img.paste(page_img, (img_x, y + 10))
            # Amber border if highlighted crop, else regular border
            clip_border = (245, 158, 11) if img_to_use == crop_path else COL_BORDER
            draw.rectangle(
                [(img_x - 2, y + 8), (img_x + page_img.width + 2, y + 10 + page_img.height + 2)],
                outline=clip_border,
                width=2,
            )
            y += page_img.height + 30
            img_loaded = True
        except Exception as e:
            logger.warning(f"Could not load news clipping: {e}")

    if not img_loaded:
        # Placeholder box
        draw.rectangle([(20, y), (PAGE_W - 20, y + 180)], fill=(226, 232, 240), outline=COL_BORDER)
        f_ph = _load_font(24)
        draw.text((PAGE_W // 2 - 140, y + 70), f"[Page {page_num} Image Not Available]", font=f_ph, fill=(148, 163, 184))
        y += 200

    # ---- KEYWORD SNIPPET HIGHLIGHT ----
    draw.rectangle([(20, y), (PAGE_W - 20, y + 6)], fill=COL_ACCENT)
    y += 16

    snippet_en = result.get("snippet_en", "")
    if snippet_en:
        draw.rounded_rectangle([(20, y), (PAGE_W - 20, y + 10 + 34 * min(len(snippet_en) // 80 + 1, 4))],
                                radius=8, fill=COL_SNIPPET_BG)
        f_snip_label = _load_font(18, bold=True)
        draw.text((36, y + 8), f"🔍  Keyword match: \"{keyword}\"", font=f_snip_label, fill=COL_SNIPPET_TEXT)
        y += 44
        f_snip = _load_font(20)
        y = _draw_wrapped_text(draw, snippet_en, 36, y, PAGE_W - 72, f_snip, COL_SNIPPET_TEXT, line_spacing=4)
        y += 16

    # ---- TRANSLATED HEADLINE ----
    draw.rectangle([(20, y), (PAGE_W - 20, y + 4)], fill=COL_BORDER)
    y += 14
    f_hl_label = _load_font(18)
    draw.text((20, y), "📰  TRANSLATED HEADLINE (English)", font=f_hl_label, fill=(71, 85, 105))
    y += 30
    f_headline = _load_font(30, bold=True)
    y = _draw_wrapped_text(draw, headline or "(No headline extracted)", 20, y, PAGE_W - 40, f_headline, COL_BODY_TEXT, line_spacing=6)
    y += 10

    # ---- ORIGINAL LANGUAGE HEADLINE (if translated) ----
    if orig_headline and orig_headline != headline:
        f_orig = _load_font(20)
        draw.text((20, y), f"Original ({orig_lang}): ", font=_load_font(18, bold=True), fill=(71, 85, 105))
        y += 24
        y = _draw_wrapped_text(draw, orig_headline, 36, y, PAGE_W - 56, f_orig, (71, 85, 105), line_spacing=4)
        y += 8

    # ---- ARTICLE BODY ----
    if body_text and body_text.strip() != headline.strip():
        draw.rectangle([(20, y), (PAGE_W - 20, y + 2)], fill=COL_BORDER)
        y += 10
        f_body_label = _load_font(18)
        draw.text((20, y), "Full Article Text (English)", font=f_body_label, fill=(71, 85, 105))
        y += 28
        f_body_font = _load_font(21)
        y = _draw_wrapped_text(draw, body_text[:1200], 20, y, PAGE_W - 40, f_body_font, COL_BODY_TEXT)
        y += 10

    # ---- FOOTNOTE BAR ----
    footer_y = PAGE_H - 70
    draw.rectangle([(0, footer_y), (PAGE_W, PAGE_H)], fill=(241, 245, 249))
    draw.line([(0, footer_y), (PAGE_W, footer_y)], fill=COL_BORDER, width=1)
    f_fn = _load_font(19)
    conf_pct = int(ocr_conf * 100)
    footnote_parts = [f"OCR Confidence: {conf_pct}%"]
    if orig_lang:
        footnote_parts.append(f"Translated from: {orig_lang}")
    footnote_parts.append(f"Source: {source_name}  ·  Page {page_num}  ·  {date_str}")
    draw.text((20, footer_y + 12), "   |   ".join(footnote_parts), font=f_fn, fill=COL_FOOTNOTE)
    draw.text((20, footer_y + 40), "VEE2 ePaper Intelligence  ·  Automated OCR Report", font=f_fn, fill=COL_ACCENT)

    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=88)
    buf.seek(0)
    return buf.read()


def build_search_results_pdf(
    results: List[Dict[str, Any]],
    keyword: str,
    date_label: Optional[str] = None,
) -> Path:
    """
    Builds a full PDF from search results and saves to data/exports/.

    Args:
        results: List of search results from pdf_search_index.search()
        keyword: The original search keyword
        date_label: Optional date string for the cover page

    Returns:
        Path to the generated PDF file
    """
    EXPORTS_DIR.mkdir(parents=True, exist_ok=True)

    # Sanitize keyword for filename
    safe_kw = re.sub(r"[^\w\s-]", "", keyword)[:40].strip().replace(" ", "_")
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = EXPORTS_DIR / f"search_{safe_kw}_{ts}.pdf"

    source_names = sorted({r.get("source_name", "") for r in results if r.get("source_name")})
    date_label = date_label or datetime.now().strftime("%d %B %Y")
    total = len(results)

    writer = PdfWriter()

    def _jpeg_to_pdf_page(jpeg_bytes: bytes) -> pypdf.PageObject:
        """Wrap a JPEG image as a single PDF page using pypdf."""
        img_reader = pypdf.PdfReader(io.BytesIO(_jpeg_bytes_to_single_page_pdf(jpeg_bytes)))
        return img_reader.pages[0]

    def _jpeg_bytes_to_single_page_pdf(jpeg_bytes: bytes) -> bytes:
        """Create a minimal single-page PDF from JPEG bytes using Pillow."""
        pil_img = Image.open(io.BytesIO(jpeg_bytes))
        w, h = pil_img.size
        pdf_buf = io.BytesIO()
        # Use Pillow's built-in PDF save (creates single page PDF)
        pil_img.save(pdf_buf, "PDF", resolution=150)
        pdf_buf.seek(0)
        return pdf_buf.read()

    # Cover page
    try:
        cover_jpeg = _build_title_page(keyword, source_names, date_label, total)
        cover_pdf_bytes = _jpeg_bytes_to_single_page_pdf(cover_jpeg)
        cover_reader = pypdf.PdfReader(io.BytesIO(cover_pdf_bytes))
        writer.add_page(cover_reader.pages[0])
    except Exception as e:
        logger.warning(f"Could not build cover page: {e}")

    # Result pages
    for idx, result in enumerate(results, start=1):
        try:
            page_jpeg = _build_result_page(result, keyword, idx, total)
            page_pdf_bytes = _jpeg_bytes_to_single_page_pdf(page_jpeg)
            page_reader = pypdf.PdfReader(io.BytesIO(page_pdf_bytes))
            writer.add_page(page_reader.pages[0])
        except Exception as e:
            logger.warning(f"Error building result page {idx}: {e}")
            continue

    # Write PDF
    try:
        with open(out_path, "wb") as f:
            writer.write(f)
        logger.info(f"Search result PDF saved: {out_path} ({total} results)")
        return out_path
    except Exception as e:
        logger.exception(f"Failed to write search PDF: {e}")
        raise
