from typing import Dict, List, Optional
from harvester.models import SourceConfig, SourceLanguage, EngineType, EditionInfo

SOURCES_REGISTRY: Dict[str, SourceConfig] = {
    # ==========================================
    # ENGLISH NEWSPAPERS (16 SOURCES)
    # ==========================================
    "toi": SourceConfig(
        id="toi",
        name="The Times of India",
        language=SourceLanguage.ENGLISH,
        category="National",
        state_region="All India",
        engine_type=EngineType.PLAYWRIGHT_FLIPBOOK,
        base_url="https://epaper.timesgroup.com",
        url_template="https://epaper.timesgroup.com/the-times-of-india/{edition}?date={YYYY}-{MM}-{DD}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="delhi"),
            EditionInfo(code="mumbai", name="Mumbai", edition_id="mumbai"),
            EditionInfo(code="bengaluru", name="Bengaluru", edition_id="bangalore"),
            EditionInfo(code="hyderabad", name="Hyderabad", edition_id="hyderabad"),
            EditionInfo(code="chennai", name="Chennai", edition_id="chennai"),
            EditionInfo(code="kolkata", name="Kolkata", edition_id="kolkata"),
        ],
        auth_required=True,
        schedule_time="05:00",
        notes="Uses PressDisplay/TimesGroup flipbook viewer. Supports session cookies.",
    ),
    "the_hindu": SourceConfig(
        id="the_hindu",
        name="The Hindu",
        language=SourceLanguage.ENGLISH,
        category="National",
        state_region="All India",
        engine_type=EngineType.PLAYWRIGHT_FLIPBOOK,
        base_url="https://epaper.thehindu.com",
        url_template="https://epaper.thehindu.com/reader/{edition}/{YYYY}/{MM}/{DD}",
        default_edition="chennai",
        available_editions=[
            EditionInfo(code="chennai", name="Chennai", edition_id="101"),
            EditionInfo(code="delhi", name="Delhi", edition_id="102"),
            EditionInfo(code="bengaluru", name="Bengaluru", edition_id="103"),
            EditionInfo(code="hyderabad", name="Hyderabad", edition_id="104"),
            EditionInfo(code="mumbai", name="Mumbai", edition_id="105"),
        ],
        auth_required=True,
        schedule_time="05:15",
        notes="Requires subscription credentials/cookies for full edition.",
    ),
    "indian_express": SourceConfig(
        id="indian_express",
        name="The Indian Express",
        language=SourceLanguage.ENGLISH,
        category="National",
        state_region="All India",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.indianexpress.com",
        url_template="https://epaper.indianexpress.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="c/delhi"),
            EditionInfo(code="mumbai", name="Mumbai", edition_id="c/mumbai"),
            EditionInfo(code="chandigarh", name="Chandigarh", edition_id="c/chandigarh"),
            EditionInfo(code="kolkata", name="Kolkata", edition_id="c/kolkata"),
            EditionInfo(code="pune", name="Pune", edition_id="c/pune"),
        ],
        auth_required=False,
        schedule_time="05:00",
        notes="High-speed JSON manifest page fetcher.",
    ),
    "hindustan_times": SourceConfig(
        id="hindustan_times",
        name="Hindustan Times",
        language=SourceLanguage.ENGLISH,
        category="National",
        state_region="North India",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.hindustantimes.com",
        url_template="https://epaper.hindustantimes.com/Home/Index?Edition={edition}&Date={DD}%2F{MM}%2F{YYYY}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="Delhi"),
            EditionInfo(code="mumbai", name="Mumbai", edition_id="Mumbai"),
            EditionInfo(code="punjab", name="Punjab", edition_id="Punjab"),
            EditionInfo(code="lucknow", name="Lucknow", edition_id="Lucknow"),
        ],
        auth_required=False,
        schedule_time="05:10",
    ),
    "economic_times": SourceConfig(
        id="economic_times",
        name="The Economic Times",
        language=SourceLanguage.ENGLISH,
        category="Business",
        state_region="All India",
        engine_type=EngineType.PLAYWRIGHT_FLIPBOOK,
        base_url="https://epaper.timesgroup.com",
        url_template="https://epaper.timesgroup.com/the-economic-times/{edition}?date={YYYY}-{MM}-{DD}",
        default_edition="mumbai",
        available_editions=[
            EditionInfo(code="mumbai", name="Mumbai", edition_id="mumbai"),
            EditionInfo(code="delhi", name="Delhi", edition_id="delhi"),
            EditionInfo(code="bengaluru", name="Bengaluru", edition_id="bangalore"),
        ],
        auth_required=True,
        schedule_time="05:30",
    ),
    "mint": SourceConfig(
        id="mint",
        name="Mint (LiveMint)",
        language=SourceLanguage.ENGLISH,
        category="Business",
        state_region="All India",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.livemint.com",
        url_template="https://epaper.livemint.com/Home/Index?Edition={edition}&Date={DD}%2F{MM}%2F{YYYY}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="Delhi"),
            EditionInfo(code="mumbai", name="Mumbai", edition_id="Mumbai"),
            EditionInfo(code="bengaluru", name="Bengaluru", edition_id="Bangalore"),
        ],
        auth_required=False,
        schedule_time="05:30",
    ),
    "financial_express": SourceConfig(
        id="financial_express",
        name="The Financial Express",
        language=SourceLanguage.ENGLISH,
        category="Business",
        state_region="All India",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.financialexpress.com",
        url_template="https://epaper.financialexpress.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="c/delhi"),
            EditionInfo(code="mumbai", name="Mumbai", edition_id="c/mumbai"),
            EditionInfo(code="bengaluru", name="Bengaluru", edition_id="c/bangalore"),
        ],
        auth_required=False,
        schedule_time="05:30",
    ),
    "business_standard": SourceConfig(
        id="business_standard",
        name="Business Standard",
        language=SourceLanguage.ENGLISH,
        category="Business",
        state_region="All India",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.business-standard.com",
        url_template="https://epaper.business-standard.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="delhi"),
            EditionInfo(code="mumbai", name="Mumbai", edition_id="mumbai"),
        ],
        auth_required=False,
        schedule_time="05:40",
    ),
    "deccan_herald": SourceConfig(
        id="deccan_herald",
        name="Deccan Herald",
        language=SourceLanguage.ENGLISH,
        category="Regional",
        state_region="Karnataka",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.deccanherald.com",
        url_template="https://epaper.deccanherald.com/Home/Index?Edition={edition}&Date={DD}%2F{MM}%2F{YYYY}",
        default_edition="bengaluru",
        available_editions=[
            EditionInfo(code="bengaluru", name="Bengaluru City", edition_id="Bengaluru"),
            EditionInfo(code="mysuru", name="Mysuru", edition_id="Mysuru"),
            EditionInfo(code="hubballi", name="Hubballi", edition_id="Hubballi"),
        ],
        auth_required=False,
        schedule_time="05:20",
    ),
    "deccan_chronicle": SourceConfig(
        id="deccan_chronicle",
        name="Deccan Chronicle",
        language=SourceLanguage.ENGLISH,
        category="Regional",
        state_region="Telangana & AP",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.deccanchronicle.com",
        url_template="https://epaper.deccanchronicle.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="hyderabad",
        available_editions=[
            EditionInfo(code="hyderabad", name="Hyderabad", edition_id="hyderabad"),
            EditionInfo(code="vijayawada", name="Vijayawada", edition_id="vijayawada"),
            EditionInfo(code="chennai", name="Chennai", edition_id="chennai"),
        ],
        auth_required=False,
        schedule_time="05:20",
    ),
    "the_tribune": SourceConfig(
        id="the_tribune",
        name="The Tribune",
        language=SourceLanguage.ENGLISH,
        category="Regional",
        state_region="Punjab & Haryana",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.tribuneindia.com",
        url_template="https://epaper.tribuneindia.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="chandigarh",
        available_editions=[
            EditionInfo(code="chandigarh", name="Chandigarh", edition_id="chandigarh"),
            EditionInfo(code="delhi", name="Delhi", edition_id="delhi"),
            EditionInfo(code="jalandhar", name="Jalandhar", edition_id="jalandhar"),
        ],
        auth_required=False,
        schedule_time="05:20",
    ),
    "the_telegraph": SourceConfig(
        id="the_telegraph",
        name="The Telegraph",
        language=SourceLanguage.ENGLISH,
        category="Regional",
        state_region="West Bengal",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.telegraphindia.com",
        url_template="https://epaper.telegraphindia.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="kolkata",
        available_editions=[
            EditionInfo(code="kolkata", name="Kolkata", edition_id="calcutta"),
            EditionInfo(code="south_bengal", name="South Bengal", edition_id="south-bengal"),
            EditionInfo(code="north_bengal", name="North Bengal", edition_id="north-bengal"),
        ],
        auth_required=False,
        schedule_time="05:30",
    ),
    "the_pioneer": SourceConfig(
        id="the_pioneer",
        name="The Pioneer",
        language=SourceLanguage.ENGLISH,
        category="Regional",
        state_region="Delhi & UP",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://dailypioneer.com/epaper",
        url_template="https://dailypioneer.com/epaper/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="delhi"),
            EditionInfo(code="lucknow", name="Lucknow", edition_id="lucknow"),
            EditionInfo(code="bhopal", name="Bhopal", edition_id="bhopal"),
        ],
        auth_required=False,
        schedule_time="05:40",
    ),
    "the_statesman": SourceConfig(
        id="the_statesman",
        name="The Statesman",
        language=SourceLanguage.ENGLISH,
        category="Regional",
        state_region="West Bengal & Delhi",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.thestatesman.com",
        url_template="https://epaper.thestatesman.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="kolkata",
        available_editions=[
            EditionInfo(code="kolkata", name="Kolkata", edition_id="kolkata"),
            EditionInfo(code="delhi", name="Delhi", edition_id="delhi"),
        ],
        auth_required=False,
        schedule_time="05:45",
    ),
    "mid_day": SourceConfig(
        id="mid_day",
        name="Mid-Day",
        language=SourceLanguage.ENGLISH,
        category="Regional",
        state_region="Mumbai",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.mid-day.com",
        url_template="https://epaper.mid-day.com/epaper/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="mumbai",
        available_editions=[
            EditionInfo(code="mumbai", name="Mumbai", edition_id="mumbai"),
            EditionInfo(code="gujarati", name="Mid-Day Gujarati", edition_id="gujarati"),
        ],
        auth_required=False,
        schedule_time="05:50",
    ),
    "free_press_journal": SourceConfig(
        id="free_press_journal",
        name="The Free Press Journal",
        language=SourceLanguage.ENGLISH,
        category="Regional",
        state_region="Maharashtra & MP",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.freepressjournal.in",
        url_template="https://epaper.freepressjournal.in/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="mumbai",
        available_editions=[
            EditionInfo(code="mumbai", name="Mumbai", edition_id="mumbai"),
            EditionInfo(code="indore", name="Indore", edition_id="indore"),
            EditionInfo(code="bhopal", name="Bhopal", edition_id="bhopal"),
        ],
        auth_required=False,
        schedule_time="05:50",
    ),

    # ==========================================
    # HINDI NEWSPAPERS (12 SOURCES)
    # ==========================================
    "dainik_bhaskar": SourceConfig(
        id="dainik_bhaskar",
        name="Dainik Bhaskar",
        language=SourceLanguage.HINDI,
        category="National",
        state_region="North & Central India",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.bhaskar.com",
        url_template="https://epaper.bhaskar.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="bhopal",
        available_editions=[
            EditionInfo(code="bhopal", name="Bhopal", edition_id="44"),
            EditionInfo(code="jaipur", name="Jaipur", edition_id="43"),
            EditionInfo(code="indore", name="Indore", edition_id="45"),
            EditionInfo(code="chandigarh", name="Chandigarh", edition_id="46"),
            EditionInfo(code="patna", name="Patna", edition_id="47"),
            EditionInfo(code="raipur", name="Raipur", edition_id="48"),
        ],
        auth_required=False,
        schedule_time="04:30",
        notes="Direct JSON manifest page CDN loader.",
    ),
    "dainik_jagran": SourceConfig(
        id="dainik_jagran",
        name="Dainik Jagran",
        language=SourceLanguage.HINDI,
        category="National",
        state_region="North India",
        engine_type=EngineType.PLAYWRIGHT_FLIPBOOK,
        base_url="https://epaper.jagran.com",
        url_template="https://epaper.jagran.com/epaper/{edition}-{DD}-{MM}-{YYYY}.html",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="delhi"),
            EditionInfo(code="kanpur", name="Kanpur", edition_id="kanpur"),
            EditionInfo(code="lucknow", name="Lucknow", edition_id="lucknow"),
            EditionInfo(code="patna", name="Patna", edition_id="patna"),
        ],
        auth_required=False,
        schedule_time="04:45",
    ),
    "amar_ujala": SourceConfig(
        id="amar_ujala",
        name="Amar Ujala",
        language=SourceLanguage.HINDI,
        category="National",
        state_region="UP, UK, HP, Delhi",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.amarujala.com",
        url_template="https://epaper.amarujala.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi NCR", edition_id="delhi-city"),
            EditionInfo(code="lucknow", name="Lucknow", edition_id="lucknow-city"),
            EditionInfo(code="dehradun", name="Dehradun", edition_id="dehradun-city"),
            EditionInfo(code="shimla", name="Shimla", edition_id="shimla-city"),
            EditionInfo(code="chandigarh", name="Chandigarh", edition_id="chandigarh-city"),
        ],
        auth_required=False,
        schedule_time="04:30",
    ),
    "navbharat_times": SourceConfig(
        id="navbharat_times",
        name="Navbharat Times",
        language=SourceLanguage.HINDI,
        category="National",
        state_region="Delhi & Mumbai",
        engine_type=EngineType.PLAYWRIGHT_FLIPBOOK,
        base_url="https://epaper.timesgroup.com",
        url_template="https://epaper.timesgroup.com/navbharat-times/{edition}?date={YYYY}-{MM}-{DD}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="delhi"),
            EditionInfo(code="mumbai", name="Mumbai", edition_id="mumbai"),
            EditionInfo(code="lucknow", name="Lucknow", edition_id="lucknow"),
        ],
        auth_required=True,
        schedule_time="05:00",
    ),
    "hindustan_hindi": SourceConfig(
        id="hindustan_hindi",
        name="Hindustan (Hindi)",
        language=SourceLanguage.HINDI,
        category="National",
        state_region="Bihar, UP, Delhi",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.livehindustan.com",
        url_template="https://epaper.livehindustan.com/Home/Index?Edition={edition}&Date={DD}%2F{MM}%2F{YYYY}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="Delhi"),
            EditionInfo(code="patna", name="Patna", edition_id="Patna"),
            EditionInfo(code="lucknow", name="Lucknow", edition_id="Lucknow"),
            EditionInfo(code="ranchi", name="Ranchi", edition_id="Ranchi"),
        ],
        auth_required=False,
        schedule_time="04:45",
    ),
    "punjab_kesari": SourceConfig(
        id="punjab_kesari",
        name="Punjab Kesari",
        language=SourceLanguage.HINDI,
        category="Regional",
        state_region="Punjab & North India",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.punjabkesari.in",
        url_template="https://epaper.punjabkesari.in/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="delhi"),
            EditionInfo(code="jalandhar", name="Jalandhar", edition_id="jalandhar"),
            EditionInfo(code="chandigarh", name="Chandigarh", edition_id="chandigarh"),
        ],
        auth_required=False,
        schedule_time="04:50",
    ),
    "prabhat_khabar": SourceConfig(
        id="prabhat_khabar",
        name="Prabhat Khabar",
        language=SourceLanguage.HINDI,
        category="Regional",
        state_region="Jharkhand & Bihar",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.prabhatkhabar.com",
        url_template="https://epaper.prabhatkhabar.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="ranchi",
        available_editions=[
            EditionInfo(code="ranchi", name="Ranchi", edition_id="ranchi"),
            EditionInfo(code="patna", name="Patna", edition_id="patna"),
            EditionInfo(code="jamshedpur", name="Jamshedpur", edition_id="jamshedpur"),
            EditionInfo(code="kolkata", name="Kolkata", edition_id="kolkata"),
        ],
        auth_required=False,
        schedule_time="05:00",
    ),
    "rajasthan_patrika": SourceConfig(
        id="rajasthan_patrika",
        name="Rajasthan Patrika",
        language=SourceLanguage.HINDI,
        category="Regional",
        state_region="Rajasthan & MP",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.patrika.com",
        url_template="https://epaper.patrika.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="jaipur",
        available_editions=[
            EditionInfo(code="jaipur", name="Jaipur", edition_id="jaipur"),
            EditionInfo(code="jodhpur", name="Jodhpur", edition_id="jodhpur"),
            EditionInfo(code="bhopal", name="Bhopal", edition_id="bhopal"),
        ],
        auth_required=False,
        schedule_time="04:30",
    ),
    "lokmat_samachar": SourceConfig(
        id="lokmat_samachar",
        name="Lokmat Samachar (Hindi)",
        language=SourceLanguage.HINDI,
        category="Regional",
        state_region="Maharashtra",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.lokmat.com",
        url_template="https://epaper.lokmat.com/lokmat-samachar/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="nagpur",
        available_editions=[
            EditionInfo(code="nagpur", name="Nagpur", edition_id="nagpur"),
            EditionInfo(code="aurangabad", name="Aurangabad", edition_id="aurangabad"),
        ],
        auth_required=False,
        schedule_time="05:15",
    ),
    "haribhoomi": SourceConfig(
        id="haribhoomi",
        name="Haribhoomi",
        language=SourceLanguage.HINDI,
        category="Regional",
        state_region="Haryana & Chhattisgarh",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.haribhoomi.com",
        url_template="https://epaper.haribhoomi.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="delhi"),
            EditionInfo(code="rohtak", name="Rohtak", edition_id="rohtak"),
            EditionInfo(code="raipur", name="Raipur", edition_id="raipur"),
        ],
        auth_required=False,
        schedule_time="05:15",
    ),
    "jansatta": SourceConfig(
        id="jansatta",
        name="Jansatta",
        language=SourceLanguage.HINDI,
        category="National",
        state_region="North India",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.jansatta.com",
        url_template="https://epaper.jansatta.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="c/delhi"),
            EditionInfo(code="kolkata", name="Kolkata", edition_id="c/kolkata"),
            EditionInfo(code="chandigarh", name="Chandigarh", edition_id="c/chandigarh"),
        ],
        auth_required=False,
        schedule_time="05:15",
    ),
    "rashtriya_sahara": SourceConfig(
        id="rashtriya_sahara",
        name="Rashtriya Sahara",
        language=SourceLanguage.HINDI,
        category="Regional",
        state_region="UP & Delhi",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.saharasamay.com",
        url_template="https://epaper.saharasamay.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="delhi",
        available_editions=[
            EditionInfo(code="delhi", name="Delhi", edition_id="delhi"),
            EditionInfo(code="lucknow", name="Lucknow", edition_id="lucknow"),
        ],
        auth_required=False,
        schedule_time="05:30",
    ),

    # ==========================================
    # TELUGU NEWSPAPERS (8 SOURCES)
    # ==========================================
    "eenadu": SourceConfig(
        id="eenadu",
        name="Eenadu",
        language=SourceLanguage.TELUGU,
        category="Regional",
        state_region="Andhra Pradesh & Telangana",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.eenadu.net",
        url_template="https://epaper.eenadu.net/Home/Index?Edition={edition}&Date={DD}%2F{MM}%2F{YYYY}",
        default_edition="hyderabad",
        available_editions=[
            EditionInfo(code="hyderabad", name="Hyderabad Main", edition_id="Hyderabad"),
            EditionInfo(code="vijayawada", name="Vijayawada Main", edition_id="Vijayawada"),
            EditionInfo(code="visakhapatnam", name="Visakhapatnam", edition_id="Visakhapatnam"),
            EditionInfo(code="tirupati", name="Tirupati", edition_id="Tirupati"),
            EditionInfo(code="warangal", name="Warangal", edition_id="Warangal"),
        ],
        auth_required=False,
        schedule_time="04:30",
        notes="High-speed CDN page stitcher.",
    ),
    "sakshi": SourceConfig(
        id="sakshi",
        name="Sakshi",
        language=SourceLanguage.TELUGU,
        category="Regional",
        state_region="Andhra Pradesh & Telangana",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.sakshi.com",
        url_template="https://epaper.sakshi.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="hyderabad",
        available_editions=[
            EditionInfo(code="hyderabad", name="Hyderabad Main", edition_id="hyderabad"),
            EditionInfo(code="amaravati", name="Amaravati", edition_id="amaravati"),
            EditionInfo(code="visakhapatnam", name="Visakhapatnam", edition_id="visakhapatnam"),
            EditionInfo(code="tirupati", name="Tirupati", edition_id="tirupati"),
        ],
        auth_required=False,
        schedule_time="04:30",
    ),
    "andhra_jyothi": SourceConfig(
        id="andhra_jyothi",
        name="Andhra Jyothi",
        language=SourceLanguage.TELUGU,
        category="Regional",
        state_region="Andhra Pradesh & Telangana",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.andhrajyothy.com",
        url_template="https://epaper.andhrajyothy.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="hyderabad",
        available_editions=[
            EditionInfo(code="hyderabad", name="Hyderabad", edition_id="hyderabad"),
            EditionInfo(code="vijayawada", name="Vijayawada", edition_id="vijayawada"),
            EditionInfo(code="visakhapatnam", name="Visakhapatnam", edition_id="visakhapatnam"),
        ],
        auth_required=False,
        schedule_time="04:45",
    ),
    "namasthe_telangana": SourceConfig(
        id="namasthe_telangana",
        name="Namasthe Telangana",
        language=SourceLanguage.TELUGU,
        category="Regional",
        state_region="Telangana",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.ntnews.com",
        url_template="https://epaper.ntnews.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="hyderabad",
        available_editions=[
            EditionInfo(code="hyderabad", name="Hyderabad", edition_id="hyderabad"),
            EditionInfo(code="warangal", name="Warangal", edition_id="warangal"),
            EditionInfo(code="karimnagar", name="Karimnagar", edition_id="karimnagar"),
        ],
        auth_required=False,
        schedule_time="05:00",
    ),
    "prajasakti": SourceConfig(
        id="prajasakti",
        name="Prajasakti",
        language=SourceLanguage.TELUGU,
        category="Regional",
        state_region="Andhra Pradesh",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.prajasakti.com",
        url_template="https://epaper.prajasakti.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="vijayawada",
        available_editions=[
            EditionInfo(code="vijayawada", name="Vijayawada", edition_id="vijayawada"),
            EditionInfo(code="visakhapatnam", name="Visakhapatnam", edition_id="visakhapatnam"),
        ],
        auth_required=False,
        schedule_time="05:15",
    ),
    "nava_telangana": SourceConfig(
        id="nava_telangana",
        name="Nava Telangana",
        language=SourceLanguage.TELUGU,
        category="Regional",
        state_region="Telangana",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.navatelangana.com",
        url_template="https://epaper.navatelangana.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="hyderabad",
        available_editions=[
            EditionInfo(code="hyderabad", name="Hyderabad", edition_id="hyderabad"),
        ],
        auth_required=False,
        schedule_time="05:15",
    ),
    "surya": SourceConfig(
        id="surya",
        name="Surya (Telugu)",
        language=SourceLanguage.TELUGU,
        category="Regional",
        state_region="AP & Telangana",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.suryaa.com",
        url_template="https://epaper.suryaa.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="hyderabad",
        available_editions=[
            EditionInfo(code="hyderabad", name="Hyderabad", edition_id="hyderabad"),
            EditionInfo(code="vijayawada", name="Vijayawada", edition_id="vijayawada"),
        ],
        auth_required=False,
        schedule_time="05:20",
    ),
    "vaartha": SourceConfig(
        id="vaartha",
        name="Vaartha",
        language=SourceLanguage.TELUGU,
        category="Regional",
        state_region="AP & Telangana",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.vaartha.com",
        url_template="https://epaper.vaartha.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="hyderabad",
        available_editions=[
            EditionInfo(code="hyderabad", name="Hyderabad", edition_id="hyderabad"),
            EditionInfo(code="vijayawada", name="Vijayawada", edition_id="vijayawada"),
        ],
        auth_required=False,
        schedule_time="05:20",
    ),

    # ==========================================
    # TAMIL NEWSPAPERS (5 SOURCES)
    # ==========================================
    "daily_thanthi": SourceConfig(
        id="daily_thanthi",
        name="Daily Thanthi (Dina Thanthi)",
        language=SourceLanguage.TAMIL,
        category="Regional",
        state_region="Tamil Nadu",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.dailythanthi.com",
        url_template="https://epaper.dailythanthi.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="chennai",
        available_editions=[
            EditionInfo(code="chennai", name="Chennai", edition_id="chennai"),
            EditionInfo(code="coimbatore", name="Coimbatore", edition_id="coimbatore"),
            EditionInfo(code="madurai", name="Madurai", edition_id="madurai"),
            EditionInfo(code="trichy", name="Trichy", edition_id="trichy"),
        ],
        auth_required=False,
        schedule_time="04:30",
    ),
    "dinamalar": SourceConfig(
        id="dinamalar",
        name="Dinamalar",
        language=SourceLanguage.TAMIL,
        category="Regional",
        state_region="Tamil Nadu",
        engine_type=EngineType.PLAYWRIGHT_FLIPBOOK,
        base_url="https://epaper.dinamalar.com",
        url_template="https://epaper.dinamalar.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="chennai",
        available_editions=[
            EditionInfo(code="chennai", name="Chennai", edition_id="chennai"),
            EditionInfo(code="madurai", name="Madurai", edition_id="madurai"),
            EditionInfo(code="coimbatore", name="Coimbatore", edition_id="coimbatore"),
        ],
        auth_required=False,
        schedule_time="04:45",
    ),
    "dinakaran": SourceConfig(
        id="dinakaran",
        name="Dinakaran",
        language=SourceLanguage.TAMIL,
        category="Regional",
        state_region="Tamil Nadu",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.dinakaran.com",
        url_template="https://epaper.dinakaran.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="chennai",
        available_editions=[
            EditionInfo(code="chennai", name="Chennai", edition_id="chennai"),
            EditionInfo(code="madurai", name="Madurai", edition_id="madurai"),
        ],
        auth_required=False,
        schedule_time="05:00",
    ),
    "hindu_tamil": SourceConfig(
        id="hindu_tamil",
        name="Hindu Tamil Thisai",
        language=SourceLanguage.TAMIL,
        category="Regional",
        state_region="Tamil Nadu",
        engine_type=EngineType.PLAYWRIGHT_FLIPBOOK,
        base_url="https://epaper.hindutamil.in",
        url_template="https://epaper.hindutamil.in/reader/{edition}/{YYYY}/{MM}/{DD}",
        default_edition="chennai",
        available_editions=[
            EditionInfo(code="chennai", name="Chennai", edition_id="chennai"),
        ],
        auth_required=True,
        schedule_time="05:15",
    ),
    "dinamani": SourceConfig(
        id="dinamani",
        name="Dinamani",
        language=SourceLanguage.TAMIL,
        category="Regional",
        state_region="Tamil Nadu",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.dinamani.com",
        url_template="https://epaper.dinamani.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="chennai",
        available_editions=[
            EditionInfo(code="chennai", name="Chennai", edition_id="c/chennai"),
            EditionInfo(code="madurai", name="Madurai", edition_id="c/madurai"),
            EditionInfo(code="coimbatore", name="Coimbatore", edition_id="c/coimbatore"),
        ],
        auth_required=False,
        schedule_time="05:00",
    ),

    # ==========================================
    # MARATHI NEWSPAPERS (6 SOURCES)
    # ==========================================
    "lokmat": SourceConfig(
        id="lokmat",
        name="Lokmat",
        language=SourceLanguage.MARATHI,
        category="Regional",
        state_region="Maharashtra & Goa",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.lokmat.com",
        url_template="https://epaper.lokmat.com/lokmat/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="mumbai",
        available_editions=[
            EditionInfo(code="mumbai", name="Mumbai Main", edition_id="mumbai-main"),
            EditionInfo(code="pune", name="Pune Main", edition_id="pune-main"),
            EditionInfo(code="nagpur", name="Nagpur Main", edition_id="nagpur-main"),
            EditionInfo(code="nashik", name="Nashik Main", edition_id="nashik-main"),
        ],
        auth_required=False,
        schedule_time="04:30",
    ),
    "loksatta": SourceConfig(
        id="loksatta",
        name="Loksatta",
        language=SourceLanguage.MARATHI,
        category="Regional",
        state_region="Maharashtra",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.loksatta.com",
        url_template="https://epaper.loksatta.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="mumbai",
        available_editions=[
            EditionInfo(code="mumbai", name="Mumbai", edition_id="c/mumbai"),
            EditionInfo(code="pune", name="Pune", edition_id="c/pune"),
            EditionInfo(code="nagpur", name="Nagpur", edition_id="c/nagpur"),
        ],
        auth_required=False,
        schedule_time="05:00",
    ),
    "maharashtra_times": SourceConfig(
        id="maharashtra_times",
        name="Maharashtra Times",
        language=SourceLanguage.MARATHI,
        category="Regional",
        state_region="Maharashtra",
        engine_type=EngineType.PLAYWRIGHT_FLIPBOOK,
        base_url="https://epaper.timesgroup.com",
        url_template="https://epaper.timesgroup.com/maharashtra-times/{edition}?date={YYYY}-{MM}-{DD}",
        default_edition="mumbai",
        available_editions=[
            EditionInfo(code="mumbai", name="Mumbai", edition_id="mumbai"),
            EditionInfo(code="pune", name="Pune", edition_id="pune"),
            EditionInfo(code="nashik", name="Nashik", edition_id="nashik"),
        ],
        auth_required=True,
        schedule_time="05:00",
    ),
    "sakaal": SourceConfig(
        id="sakaal",
        name="Sakaal",
        language=SourceLanguage.MARATHI,
        category="Regional",
        state_region="Maharashtra",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.esakal.com",
        url_template="https://epaper.esakal.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="pune",
        available_editions=[
            EditionInfo(code="pune", name="Pune", edition_id="pune"),
            EditionInfo(code="mumbai", name="Mumbai", edition_id="mumbai"),
            EditionInfo(code="kolhapur", name="Kolhapur", edition_id="kolhapur"),
        ],
        auth_required=False,
        schedule_time="04:45",
    ),
    "saamana": SourceConfig(
        id="saamana",
        name="Saamana",
        language=SourceLanguage.MARATHI,
        category="Regional",
        state_region="Maharashtra",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.saamana.com",
        url_template="https://epaper.saamana.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="mumbai",
        available_editions=[
            EditionInfo(code="mumbai", name="Mumbai", edition_id="mumbai"),
            EditionInfo(code="pune", name="Pune", edition_id="pune"),
            EditionInfo(code="nashik", name="Nashik", edition_id="nashik"),
        ],
        auth_required=False,
        schedule_time="05:15",
    ),
    "pudhari": SourceConfig(
        id="pudhari",
        name="Pudhari",
        language=SourceLanguage.MARATHI,
        category="Regional",
        state_region="Maharashtra & Goa",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.pudhari.news",
        url_template="https://epaper.pudhari.news/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="kolhapur",
        available_editions=[
            EditionInfo(code="kolhapur", name="Kolhapur", edition_id="kolhapur"),
            EditionInfo(code="pune", name="Pune", edition_id="pune"),
            EditionInfo(code="mumbai", name="Mumbai", edition_id="mumbai"),
        ],
        auth_required=False,
        schedule_time="05:15",
    ),

    # ==========================================
    # BENGALI NEWSPAPERS (4 SOURCES)
    # ==========================================
    "anandabazar": SourceConfig(
        id="anandabazar",
        name="Anandabazar Patrika (ABP)",
        language=SourceLanguage.BENGALI,
        category="Regional",
        state_region="West Bengal",
        engine_type=EngineType.PLAYWRIGHT_FLIPBOOK,
        base_url="https://epaper.anandabazar.com",
        url_template="https://epaper.anandabazar.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="kolkata",
        available_editions=[
            EditionInfo(code="kolkata", name="Kolkata", edition_id="kolkata"),
            EditionInfo(code="north_bengal", name="North Bengal", edition_id="north-bengal"),
        ],
        auth_required=False,
        schedule_time="05:00",
    ),
    "bartaman": SourceConfig(
        id="bartaman",
        name="Bartaman Patrika",
        language=SourceLanguage.BENGALI,
        category="Regional",
        state_region="West Bengal",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://bartamanpatrika.org",
        url_template="https://bartamanpatrika.org/epaper/{YYYY}/{MM}/{DD}",
        default_edition="kolkata",
        available_editions=[
            EditionInfo(code="kolkata", name="Kolkata", edition_id="kolkata"),
        ],
        auth_required=False,
        schedule_time="05:15",
    ),
    "ei_samay": SourceConfig(
        id="ei_samay",
        name="Ei Samay",
        language=SourceLanguage.BENGALI,
        category="Regional",
        state_region="West Bengal",
        engine_type=EngineType.PLAYWRIGHT_FLIPBOOK,
        base_url="https://epaper.timesgroup.com",
        url_template="https://epaper.timesgroup.com/ei-samay/{edition}?date={YYYY}-{MM}-{DD}",
        default_edition="kolkata",
        available_editions=[
            EditionInfo(code="kolkata", name="Kolkata", edition_id="kolkata"),
        ],
        auth_required=True,
        schedule_time="05:15",
    ),
    "sangbad_pratidin": SourceConfig(
        id="sangbad_pratidin",
        name="Sangbad Pratidin",
        language=SourceLanguage.BENGALI,
        category="Regional",
        state_region="West Bengal",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.sangbadpratidin.in",
        url_template="https://epaper.sangbadpratidin.in/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="kolkata",
        available_editions=[
            EditionInfo(code="kolkata", name="Kolkata", edition_id="kolkata"),
        ],
        auth_required=False,
        schedule_time="05:30",
    ),

    # ==========================================
    # GUJARATI NEWSPAPERS (3 SOURCES)
    # ==========================================
    "gujarat_samachar": SourceConfig(
        id="gujarat_samachar",
        name="Gujarat Samachar",
        language=SourceLanguage.GUJARATI,
        category="Regional",
        state_region="Gujarat & Mumbai",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.gujaratsamachar.com",
        url_template="https://epaper.gujaratsamachar.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="ahmedabad",
        available_editions=[
            EditionInfo(code="ahmedabad", name="Ahmedabad", edition_id="ahmedabad"),
            EditionInfo(code="surat", name="Surat", edition_id="surat"),
            EditionInfo(code="vadodara", name="Vadodara", edition_id="vadodara"),
            EditionInfo(code="mumbai", name="Mumbai", edition_id="mumbai"),
        ],
        auth_required=False,
        schedule_time="04:45",
    ),
    "sandesh": SourceConfig(
        id="sandesh",
        name="Sandesh",
        language=SourceLanguage.GUJARATI,
        category="Regional",
        state_region="Gujarat",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://sandeshepaper.in",
        url_template="https://sandeshepaper.in/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="ahmedabad",
        available_editions=[
            EditionInfo(code="ahmedabad", name="Ahmedabad", edition_id="ahmedabad"),
            EditionInfo(code="surat", name="Surat", edition_id="surat"),
            EditionInfo(code="rajkot", name="Rajkot", edition_id="rajkot"),
        ],
        auth_required=False,
        schedule_time="05:00",
    ),
    "divya_bhaskar": SourceConfig(
        id="divya_bhaskar",
        name="Divya Bhaskar",
        language=SourceLanguage.GUJARATI,
        category="Regional",
        state_region="Gujarat",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.divyabhaskar.co.in",
        url_template="https://epaper.divyabhaskar.co.in/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="ahmedabad",
        available_editions=[
            EditionInfo(code="ahmedabad", name="Ahmedabad", edition_id="ahmedabad"),
            EditionInfo(code="surat", name="Surat", edition_id="surat"),
            EditionInfo(code="rajkot", name="Rajkot", edition_id="rajkot"),
        ],
        auth_required=False,
        schedule_time="04:30",
    ),

    # ==========================================
    # KANNADA NEWSPAPERS (4 SOURCES)
    # ==========================================
    "prajavani": SourceConfig(
        id="prajavani",
        name="Prajavani",
        language=SourceLanguage.KANNADA,
        category="Regional",
        state_region="Karnataka",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.prajavani.net",
        url_template="https://epaper.prajavani.net/Home/Index?Edition={edition}&Date={DD}%2F{MM}%2F{YYYY}",
        default_edition="bengaluru",
        available_editions=[
            EditionInfo(code="bengaluru", name="Bengaluru", edition_id="Bengaluru"),
            EditionInfo(code="mysuru", name="Mysuru", edition_id="Mysuru"),
            EditionInfo(code="hubballi", name="Hubballi", edition_id="Hubballi"),
        ],
        auth_required=False,
        schedule_time="05:00",
    ),
    "vijayavani": SourceConfig(
        id="vijayavani",
        name="Vijayavani",
        language=SourceLanguage.KANNADA,
        category="Regional",
        state_region="Karnataka",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epapervijayavani.in",
        url_template="https://epapervijayavani.in/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="bengaluru",
        available_editions=[
            EditionInfo(code="bengaluru", name="Bengaluru", edition_id="bengaluru"),
            EditionInfo(code="hubballi", name="Hubballi", edition_id="hubballi"),
        ],
        auth_required=False,
        schedule_time="05:15",
    ),
    "vijaya_karnataka": SourceConfig(
        id="vijaya_karnataka",
        name="Vijaya Karnataka",
        language=SourceLanguage.KANNADA,
        category="Regional",
        state_region="Karnataka",
        engine_type=EngineType.PLAYWRIGHT_FLIPBOOK,
        base_url="https://epaper.timesgroup.com",
        url_template="https://epaper.timesgroup.com/vijaya-karnataka/{edition}?date={YYYY}-{MM}-{DD}",
        default_edition="bengaluru",
        available_editions=[
            EditionInfo(code="bengaluru", name="Bengaluru", edition_id="bangalore"),
            EditionInfo(code="mysuru", name="Mysuru", edition_id="mysore"),
        ],
        auth_required=True,
        schedule_time="05:15",
    ),
    "kannada_prabha": SourceConfig(
        id="kannada_prabha",
        name="Kannada Prabha",
        language=SourceLanguage.KANNADA,
        category="Regional",
        state_region="Karnataka",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.kannadaprabha.in",
        url_template="https://epaper.kannadaprabha.in/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="bengaluru",
        available_editions=[
            EditionInfo(code="bengaluru", name="Bengaluru", edition_id="bengaluru"),
        ],
        auth_required=False,
        schedule_time="05:30",
    ),

    # ==========================================
    # MALAYALAM NEWSPAPERS (3 SOURCES)
    # ==========================================
    "malayala_manorama": SourceConfig(
        id="malayala_manorama",
        name="Malayala Manorama",
        language=SourceLanguage.MALAYALAM,
        category="Regional",
        state_region="Kerala",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.manoramaonline.com",
        url_template="https://epaper.manoramaonline.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="kottayam",
        available_editions=[
            EditionInfo(code="kottayam", name="Kottayam", edition_id="kottayam"),
            EditionInfo(code="kochi", name="Kochi", edition_id="kochi"),
            EditionInfo(code="thiruvananthapuram", name="Thiruvananthapuram", edition_id="tvm"),
            EditionInfo(code="kozhikode", name="Kozhikode", edition_id="kozhikode"),
        ],
        auth_required=False,
        schedule_time="04:30",
    ),
    "mathrubhumi": SourceConfig(
        id="mathrubhumi",
        name="Mathrubhumi",
        language=SourceLanguage.MALAYALAM,
        category="Regional",
        state_region="Kerala",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.mathrubhumi.com",
        url_template="https://epaper.mathrubhumi.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="kozhikode",
        available_editions=[
            EditionInfo(code="kozhikode", name="Kozhikode", edition_id="kozhikode"),
            EditionInfo(code="kochi", name="Kochi", edition_id="kochi"),
            EditionInfo(code="thiruvananthapuram", name="Thiruvananthapuram", edition_id="tvm"),
        ],
        auth_required=False,
        schedule_time="04:45",
    ),
    "deshabhimani": SourceConfig(
        id="deshabhimani",
        name="Deshabhimani",
        language=SourceLanguage.MALAYALAM,
        category="Regional",
        state_region="Kerala",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.deshabhimani.com",
        url_template="https://epaper.deshabhimani.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="thiruvananthapuram",
        available_editions=[
            EditionInfo(code="thiruvananthapuram", name="Thiruvananthapuram", edition_id="tvm"),
            EditionInfo(code="kochi", name="Kochi", edition_id="kochi"),
        ],
        auth_required=False,
        schedule_time="05:00",
    ),

    # ==========================================
    # ODIA, PUNJABI, URDU (3 SOURCES)
    # ==========================================
    "sambad": SourceConfig(
        id="sambad",
        name="Sambad (Odia)",
        language=SourceLanguage.ODIA,
        category="Regional",
        state_region="Odisha",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.sambad.in",
        url_template="https://epaper.sambad.in/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="bhubaneswar",
        available_editions=[
            EditionInfo(code="bhubaneswar", name="Bhubaneswar", edition_id="bhubaneswar"),
            EditionInfo(code="cuttack", name="Cuttack", edition_id="cuttack"),
        ],
        auth_required=False,
        schedule_time="05:15",
    ),
    "ajit": SourceConfig(
        id="ajit",
        name="Daily Ajit (Punjabi)",
        language=SourceLanguage.PUNJABI,
        category="Regional",
        state_region="Punjab",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.ajitjalandhar.com",
        url_template="https://epaper.ajitjalandhar.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="jalandhar",
        available_editions=[
            EditionInfo(code="jalandhar", name="Jalandhar", edition_id="jalandhar"),
        ],
        auth_required=False,
        schedule_time="05:15",
    ),
    "inquilab": SourceConfig(
        id="inquilab",
        name="The Inquilab (Urdu)",
        language=SourceLanguage.URDU,
        category="Regional",
        state_region="Mumbai & North India",
        engine_type=EngineType.MANIFEST_API,
        base_url="https://epaper.inquilab.com",
        url_template="https://epaper.inquilab.com/{edition}/{YYYY}-{MM}-{DD}",
        default_edition="mumbai",
        available_editions=[
            EditionInfo(code="mumbai", name="Mumbai", edition_id="mumbai"),
            EditionInfo(code="delhi", name="Delhi", edition_id="delhi"),
        ],
        auth_required=False,
        schedule_time="05:30",
    ),
}


def get_source(source_id: str) -> Optional[SourceConfig]:
    return SOURCES_REGISTRY.get(source_id)


def list_sources(
    language: Optional[str] = None,
    category: Optional[str] = None,
    active_only: bool = False
) -> List[SourceConfig]:
    sources = list(SOURCES_REGISTRY.values())
    if language:
        sources = [s for s in sources if s.language.value.lower() == language.lower()]
    if category:
        sources = [s for s in sources if s.category.lower() == category.lower()]
    if active_only:
        sources = [s for s in sources if s.active]
    return sources


def resolve_url(source: SourceConfig, target_date_str: str, edition_code: Optional[str] = None) -> str:
    """
    Interpolates dynamic date tokens {YYYY}, {MM}, {DD} and {edition}
    """
    edition = edition_code or source.default_edition
    parts = target_date_str.split("-")
    year, month, day = parts[0], parts[1], parts[2]
    
    url = source.url_template.replace("{YYYY}", year)\
                             .replace("{MM}", month)\
                             .replace("{DD}", day)\
                             .replace("{edition}", edition)
    return url
